"""
Core Pydantic v2 data models for Revenue Recovery Agent.

Includes:
- FailedPayment: Payment failure record
- AuditLogEntry: Audit trace entry per agent node execution
- FailReason: Failure root-cause enumeration
- PaymentStatus: Lifecycle status of recovery attempt
- InterventionAction: Bounded recovery intervention actions
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field


# ── Enumerations ──────────────────────────────────────────────────

class FailReason(str, Enum):
    """Specific failure reasons for recurring / mandate payments."""
    INSUFFICIENT_FUNDS = "insufficient_funds"
    EXPIRED_CARD = "expired_card"
    BANK_DECLINE = "bank_decline"
    MANDATE_REVOKED = "mandate_revoked"
    TECHNICAL_ERROR = "technical_error"


class PaymentStatus(str, Enum):
    """Lifecycle status of a failed payment recovery process."""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    RECOVERED = "recovered"
    ESCALATED = "escalated"
    STOPPED = "stopped"
    AWAITING_PROMISE = "awaiting_promise"


class InterventionAction(str, Enum):
    """Bounded recovery actions executed or recommended by the agent."""
    RETRY_NOW = "retry_now"
    RETRY_LATER = "retry_later"
    SWITCH_PAYMENT_METHOD = "switch_payment_method"
    ESCALATE_HUMAN = "escalate_human"
    STOP_NO_ACTION = "stop_no_action"


# ── Core Data Models ──────────────────────────────────────────────

class FailedPaymentBase(BaseModel):
    """Base fields for a failed subscription / mandate payment."""
    payment_id: str = Field(..., description="Unique payment identifier (e.g. pay_xxx)")
    customer_id: str = Field(..., description="Customer identifier (e.g. cust_xxx)")
    customer_name: str = Field(..., description="Full name of customer")
    amount: float = Field(..., gt=0, description="Amount in INR")
    subscription_id: str = Field(..., description="Subscription / mandate identifier (e.g. sub_xxx)")
    fail_reason: FailReason = Field(..., description="Categorized failure reason")
    fail_timestamp: datetime = Field(..., description="UTC Timestamp when the payment attempt failed")
    retry_count: int = Field(default=0, ge=0, description="Number of retries attempted")
    status: PaymentStatus = Field(default=PaymentStatus.PENDING, description="Current recovery lifecycle status")


class FailedPayment(FailedPaymentBase):
    """Failed payment model with serialization & ORM config."""
    model_config = {
        "from_attributes": True,
        "json_schema_extra": {
            "example": {
                "payment_id": "pay_failed_101",
                "customer_id": "cust_82910",
                "customer_name": "Aarav Sharma",
                "amount": 999.00,
                "subscription_id": "sub_premium_monthly",
                "fail_reason": "insufficient_funds",
                "fail_timestamp": "2026-08-20T10:30:00Z",
                "retry_count": 0,
                "status": "pending",
            }
        },
    }


class AuditLogEntryBase(BaseModel):
    """Base schema for an audit log entry recorded during recovery execution."""
    payment_id: str = Field(..., description="Associated payment ID")
    node_name: str = Field(..., description="Agent workflow node name (e.g., classify_failure)")
    input_snapshot: Dict[str, Any] = Field(default_factory=dict, description="State/input snapshot passed to node")
    decision: str = Field(..., description="Action or classification decided by the node")
    reason: str = Field(..., description="Detailed textual rationale for the decision")
    tool_called: Optional[str] = Field(default=None, description="External tool or API invoked (if any)")
    tool_result: Optional[Dict[str, Any]] = Field(default=None, description="Result returned by tool (if any)")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Timestamp of the audit entry")


class AuditLogEntry(AuditLogEntryBase):
    """Audit log model with database ID and ORM compatibility."""
    id: Optional[int] = Field(default=None, description="Unique primary key (generated by DB)")

    model_config = {
        "from_attributes": True,
    }
